#!/usr/bin/env bash
set -euo pipefail

# EventPulse Field Ops — Raspberry Pi installer
#
# This script installs the EventPulse edge-agent as a systemd-managed Docker container.
#
# Usage (recommended):
#   sudo bash field_ops/rpi/install.sh \
#     --api-base-url "https://YOUR_CLOUD_RUN_URL" \
#     --enroll-token "..."
#
# Notes:
# - Uses bootstrap enrollment by default (EDGE_ENROLL_TOKEN). The agent will persist the
#   provisioned per-device token to the spool directory.
# - Designed for Raspberry Pi OS 64-bit (Debian-based).

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "ERROR: run as root (use sudo)" >&2
  exit 1
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

ENV_DIR="/etc/eventpulse-edge"
ENV_FILE="${ENV_DIR}/edge.env"
SPOOL_DIR="/var/lib/eventpulse-edge/spool"

API_BASE_URL=""
ENROLL_TOKEN=""
DEVICE_TOKEN=""
DEVICE_ID=""
DEVICE_LABEL=""
IMAGE=""
SENSOR_MODE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --api-base-url)
      API_BASE_URL="${2:-}"; shift 2 ;;
    --enroll-token)
      ENROLL_TOKEN="${2:-}"; shift 2 ;;
    --device-token)
      DEVICE_TOKEN="${2:-}"; shift 2 ;;
    --device-id)
      DEVICE_ID="${2:-}"; shift 2 ;;
    --device-label)
      DEVICE_LABEL="${2:-}"; shift 2 ;;
    --image)
      IMAGE="${2:-}"; shift 2 ;;
    --sensor-mode)
      SENSOR_MODE="${2:-}"; shift 2 ;;
    -h|--help)
      sed -n '1,120p' "$0"; exit 0 ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

# -----------------------------
# Dependencies
# -----------------------------

echo "[field-ops] installing dependencies…" >&2
apt-get update -y >/dev/null
apt-get install -y --no-install-recommends ca-certificates curl gnupg lsb-release >/dev/null

if ! command -v docker >/dev/null 2>&1; then
  echo "[field-ops] docker not found; installing via get.docker.com…" >&2
  curl -fsSL https://get.docker.com | sh
fi

# Ensure the daemon is started
systemctl enable --now docker >/dev/null

# -----------------------------
# Install files
# -----------------------------

echo "[field-ops] creating directories…" >&2
install -d -m 0700 "${ENV_DIR}"
install -d -m 0750 "${SPOOL_DIR}"

# Ensure container user (uid 10001) can write to spool.
chown -R 10001:10001 "${SPOOL_DIR}" || true

echo "[field-ops] installing systemd unit + helpers…" >&2
install -m 0644 "${SCRIPT_DIR}/eventpulse-edge-agent.service" /etc/systemd/system/eventpulse-edge-agent.service
install -m 0755 "${SCRIPT_DIR}/eventpulse-edge-agent-run" /usr/local/bin/eventpulse-edge-agent-run
install -m 0755 "${SCRIPT_DIR}/eventpulse-edge-agent-update" /usr/local/bin/eventpulse-edge-agent-update

# -----------------------------
# Configure env file
# -----------------------------

if [[ ! -f "${ENV_FILE}" ]]; then
  echo "[field-ops] writing ${ENV_FILE}…" >&2

  {
    echo "# Auto-generated by field_ops/rpi/install.sh"
    echo "# You can edit this file later and restart: sudo systemctl restart eventpulse-edge-agent"
    echo ""
    if [[ -n "${API_BASE_URL}" ]]; then
      echo "EDGE_API_BASE_URL=${API_BASE_URL}"
    else
      echo "# EDGE_API_BASE_URL=https://YOUR_CLOUD_RUN_URL"
    fi

    if [[ -n "${DEVICE_ID}" ]]; then
      echo "EDGE_DEVICE_ID=${DEVICE_ID}"
    fi
    if [[ -n "${DEVICE_LABEL}" ]]; then
      echo "EDGE_DEVICE_LABEL=${DEVICE_LABEL}"
    fi

    echo "EDGE_DATASET=edge_telemetry"
    echo "EDGE_SOURCE=edge_agent"
    echo "EDGE_UPLOAD_MODE=signed_url"
    echo "EDGE_SPOOL_DIR=/data/spool"
    echo "EDGE_AGENT_PULL_POLICY=missing"

    if [[ -n "${IMAGE}" ]]; then
      echo "EDGE_AGENT_IMAGE=${IMAGE}"
    fi

    if [[ -n "${ENROLL_TOKEN}" ]]; then
      echo "EDGE_ENROLL_TOKEN=${ENROLL_TOKEN}"
    elif [[ -n "${DEVICE_TOKEN}" ]]; then
      echo "EDGE_DEVICE_TOKEN=${DEVICE_TOKEN}"
    else
      echo "# EDGE_ENROLL_TOKEN=PASTE_EDGE_ENROLL_TOKEN"
      echo "# (or) EDGE_DEVICE_TOKEN=PASTE_DEVICE_TOKEN"
    fi

    if [[ -n "${SENSOR_MODE}" ]]; then
      echo "EDGE_SENSOR_MODE=${SENSOR_MODE}"
    else
      echo "EDGE_SENSOR_MODE=simulated"
    fi

    echo "EDGE_SAMPLE_HZ=2.0"
    echo "EDGE_HEARTBEAT_SECONDS=30"
    echo "EDGE_UPLOAD_INTERVAL_SECONDS=10"
    echo "EDGE_MAX_SPOOL_MB=256"
    echo "EDGE_MAX_SPOOL_FILES=2000"
    echo "EDGE_MAX_RETRIES_PER_FILE=12"
    echo "EDGE_REQUEST_TIMEOUT_SECONDS=30"
  } >"${ENV_FILE}"

  chmod 0600 "${ENV_FILE}"
else
  echo "[field-ops] ${ENV_FILE} already exists; leaving it unchanged." >&2
fi

# -----------------------------
# Start service
# -----------------------------

echo "[field-ops] enabling + starting service…" >&2
systemctl daemon-reload
systemctl enable --now eventpulse-edge-agent.service

echo "[field-ops] done." >&2

echo "" >&2
echo "Next steps:" >&2
echo "  1) Edit config (if needed): sudo nano ${ENV_FILE}" >&2
echo "  2) Restart:               sudo systemctl restart eventpulse-edge-agent" >&2
echo "  3) Logs:                  sudo journalctl -u eventpulse-edge-agent -f" >&2
echo "  4) Status:                sudo systemctl status eventpulse-edge-agent" >&2
